dist: trusty
language: node_js
cache: yarn
notifications:
  email: false
node_js:
  - node
  - v12
  - v10
env:
  - PPTR_OVERRIDE_VERSION=1.6.x
  - PPTR_OVERRIDE_VERSION=1.8.x
  - PPTR_OVERRIDE_VERSION=1.12.x
  - PPTR_OVERRIDE_VERSION=latest
before_install:
  - npm install -g yarn coveralls nyc @patrickhulce/scripts
before_script:
  - yarn add -D "puppeteer@${PPTR_OVERRIDE_VERSION}" "@types/puppeteer@${PPTR_OVERRIDE_VERSION}"
script:
  - yarn rebuild
  - yarn test:lint
  - yarn test:unit --coverage --runInBand --verbose
after_success:
  - cat coverage/lcov.info | coveralls || echo 'Failed to upload to coveralls...'
