dist: trusty
language: node_js
notifications:
  email: false
node_js:
  - v14
  - v10
env:
  - PPTR_OVERRIDE_VERSION=1.6.x
  - PPTR_OVERRIDE_VERSION=1.8.x
  - PPTR_OVERRIDE_VERSION=1.12.x
  - PPTR_OVERRIDE_VERSION=2.x.x
  - PPTR_OVERRIDE_VERSION=3.x.x
  - PPTR_OVERRIDE_VERSION=4.x.x
  - PPTR_OVERRIDE_VERSION=5.x.x
  - PPTR_OVERRIDE_VERSION=latest
before_install:
  - npm install -g coveralls nyc @patrickhulce/scripts
before_script:
  - npm install -D "puppeteer@${PPTR_OVERRIDE_VERSION}"
  - npm install -D "@types/puppeteer@${PPTR_OVERRIDE_VERSION}" || echo "No types available"
script:
  - npm run rebuild
  - npm run test:lint
  - npm run test:unit --coverage --runInBand --verbose
after_success:
  - cat coverage/lcov.info | coveralls || echo 'Failed to upload to coveralls...'
